import Header from '@/components/global/Header';
import TopBar from '@/components/global/TopBar';
import 'bootstrap/dist/css/bootstrap.min.css';
import { inter } from './fonts';
import './globals.css';
import "./reset.css";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

 const RootLayout = ({ children }) => {
  return (
      <html lang="en">
          <body className={`${inter.className}`}>
          <TopBar/>
          <Header/>
            {children}
            {/* <Footer/> */}
          </body>
      </html>
  );
}

export default RootLayout;
